### ISSUE TITLE
Compile error when building with Visual Studio 2012

### ISSUE THREAD

**Issue by embeh** [cheind/dest#1]
This is what I get when trying to build all, using Visual Studio 2012:

dest\inc\dest/core/regressor.h(63): error C2248: 'std::unique_ptr<_Ty>::operator =' : cannot access private member declared in class 'std::unique_ptr<_Ty>'
1>          with
1>          [
1>              _Ty=dest::core::Regressor::data
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\memory(1448) : see declaration of 'std::unique_ptr<_Ty>::operator ='
1>          with
1>          [
1>              _Ty=dest::core::Regressor::data
1>          ]
1>          This diagnostic occurred in the compiler generated function 'dest::core::Regressor &dest::core::Regressor::operator =(const dest::core::Regressor &)'

**Comment by cheind** [comment]
Thanks for noting. Will have a look tomorrow when I have access to a machine with VS 2012. Did you try the master branch or one of the release tags?

**Comment by cheind** [comment]
Thinking about the error: it seems like you are trying to assign a regressor to another variable by value. This is currently not implemented. Maybe you can use references or shared_ptr?

**Comment by embeh** [comment]
master branch, downloaded yesterday as zip

**Comment by embeh** [comment]
I get that error when trying to build the examples from the source...

**Comment by cheind** [comment]
Thanks, will have a look

**Comment by cheind** [comment]
I understand what will probably cause the issue (failure of providing an explicit assignment operator for PIMPL idiom), but I fail to reproduce your issue with VS 2013 (which is  Microsoft Visual Studio Professional 2013, Version 12.0.21005.1 REL). Are you referring to VS 2012, i.e MSVC 11?

**Comment by embeh** [comment]
Correct, I got the error trying to build in Visual Studio Professional 2012, version 11

**Comment by cheind** [comment]
Hi,

I don't have access to VS 2012 currently. Would you mind creating a pull request with a proposed fix? I think its mainly due to not explicitly implementing the assignment operator= for the Regressor class. The assignment operator should deep-copy the values in the data struct pointed to by _data.

**Comment by embeh** [comment]
I would fix it - if I knew how ;-)

**Comment by cheind** [comment]
Latest master branch should fix the issues you have.

**Comment by cheind** [comment]
Latest master branch should resolve your issues.
