### ISSUE TITLE
Build failed in VS2015

### ISSUE THREAD

**Issue by HyunmokMoon** [cheind/dest#12]
Hello,

I cmake with OpenCV,
and I want to build from MSVS 2015 after cmake build result.
(without OpenMP)

there are link error. 
module machine type x64 conflicts with target machine type x86.
dest_align project.
opencv_world320d.lib (opencv_world320d.dll)

How can I build project?

Thank you.

**Comment by cheind** [comment]
Looks like you are building for 64bit but trying to link against 32bit OpenCV (or vice versa)

**Comment by cheind** [comment]
Closing, reopen if required.
