### ISSUE TITLE
How to use this dest_tracker_VJ_HELEN.bin file?

### ISSUE THREAD

**Issue by fedora2008** [cheind/dest#13]
Hi,great project,
I follow the instruction , and compiled project ok, and use the demos like this,
./dest_track_video -t dest_tracker_VJ_HELEN.bin -d classifier_frontalface_alt2.xml 0
Abort trap: 6

I want to know , where is the file destcv.bin? i need to train it by myself? how to use the file  dest_tracker_VJ_HELEN.bin?

**Comment by cheind** [comment]
You have 2 choices. Use a pre-trained model (dest_tracker_VJ_HELEN.bin) or train yourself. In case you want to use a pre-trained model you usually pass this filename per `-t dest_tracker_VJ_HELEN.bin`. It is then assumed that a file named `dest_tracker_VJ_HELEN.bin` resides in the working directory (usually the directory you start the app from).
