### ISSUE TITLE
dest_evaluate can't work with dest.bin

### ISSUE THREAD

**Issue by qianyunw** [cheind/dest#15]
I tried different max depths with "dest_train --load-mirrored --load-max-size 640 --rectangles helen\trainset100\rectangles.csv --create-num-shapes 60 --train-num-pixels 600 --train-num-splits 40 --train-max-depth X --train-learn 0.15 helen\trainset100"

but  when train-max-depth > 6, dest_evaluate can't work, and it said "Failed to load tracker."

It has bothered  me for three days, thank you so much!

**Comment by cheind** [comment]
If it can't load the tracker it seems to be that the tracker hasn't been written to disk. Could you verify if training gives you any error or does not write the tracking file?

**Comment by qianyunw** [comment]
Thank you so much!
I found it is because vertifier._max_tables in dest_evaluate is smaller than that in dest.bin. When I set _max_tables  to a bigger number, It works! Thank you!

**Comment by cheind** [comment]
hmm, interesting. what exactly did you do? Could you share a code snippet?

wangdayan <notifications@github.com> schrieb am Mo., 12. März 2018 um
06:40 Uhr:

**Comment by qianyunw** [comment]
Sure. In tracker.cpp I changed from:
 "flatbuffers::Verifier v(reinterpret_cast<const uint8_t*>(buf.data()), buf.size());" 
to 
"flatbuffers::Verifier v(reinterpret_cast<const uint8_t*>(buf.data()), buf.size(), 64, 900000000000);"

**Comment by cheind** [comment]
Thanks, I will consider changing the code, or, at least keep this in the back of my mind.
