### ISSUE TITLE
Problem in running the code

### ISSUE THREAD

**Issue by Sun1718** [cheind/dest#3]
Hi cheind,

Thanks for sharing your codes. I've compiled it using visual studio 2015 successfully. 
This error was appeared in output window when I run it:

'dest_tests.exe' (Win32): Loaded 'D:\Programming\Programming_Morteza\dest-master\build\Release\dest_tests.exe'. Module was built without symbols.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-runtime-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-heap-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-utility-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-stdio-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-filesystem-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-string-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-time-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-math-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-locale-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-multibyte-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-convert-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\api-ms-win-crt-environment-l1-1-0.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'dest_tests.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
The program '[8144] dest_tests.exe' has exited with code 0 (0x0).

Regards.
Morteza

**Comment by cheind** [comment]
Please try to build and run in Release mode.

**Comment by Sun1718** [comment]
Thanks for your reply, i run it in release mode but the same error was appeared.

**Comment by cheind** [comment]
Not sure what error you are referring to. The only thing i can see from your logs are missing pdb files which is just a hint not necessarily an error. What happens when you run one of the examples?

**Comment by Sun1718** [comment]
So thanks. It solved. I found that any of example projects was build using cmake. I recompiled it again and enable Opencv. The examples work without problem.It is very nice.

I've another question, I want to use video tracker in web based application. How can I convert code to client side web based code. dest_tracker_VJ_ibug.bin is about  48M and it is heavy to load in web applications. How can I use it?

**Comment by cheind** [comment]
I would advise to provide a web-service, i.e a service that runs on some dedicated host / port and to which clients communicate with a JSON like API. That way all the heavy lifting is done on the server side and not the client side. 

closes #3

**Comment by cheind** [comment]
I would advise to provide a web-service, i.e a service that runs on some dedicated host / port and to which clients communicate via a JSON like API. That way all the heavy lifting is done on the server side and not the client side.
