### ISSUE TITLE
when I use ubuntu10.4 ,I meet error

### ISSUE THREAD

**Issue by anthonyyuan** [cheind/dest#4]
make
[  3%] Building CXX object CMakeFiles/dest.dir/src/io/database_io.cpp.o
/home/anthony/app/dest-master_2/src/io/database_io.cpp: In member function ‘virtual bool dest::io::DatabaseLoaderIBug::loadShape(std::size_t, cv::Size, dest::core::Shape&)’:
/home/anthony/app/dest-master_2/src/io/database_io.cpp:371:22: error: use of deleted function ‘std::basic_stringstream<char>& std::basic_stringstream<char>::operator=(const std::basic_stringstream<char>&)’
                 str1 = std::stringstream(line);
                      ^
In file included from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:0:
/usr/include/c++/4.8/sstream:502:11: note: ‘std::basic_stringstream<char>& std::basic_stringstream<char>::operator=(const std::basic_stringstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/sstream:502:11: error: use of deleted function ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.8/sstream:38:0,
                 from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:
/usr/include/c++/4.8/istream:795:11: note: ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.8/istream:795:11: error: use of deleted function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’
/usr/include/c++/4.8/istream:58:11: note: ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8/istream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8/ios:42:0,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:
/usr/include/c++/4.8/bits/ios_base.h:795:5: error: ‘std::ios_base& std::ios_base::operator=(const std::ios_base&)’ is private
     operator=(const ios_base&);
     ^
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8/sstream:38:0,
                 from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:
/usr/include/c++/4.8/istream:795:11: error: use of deleted function ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’
     class basic_iostream
           ^
In file included from /usr/include/c++/4.8/istream:39:0,
                 from /usr/include/c++/4.8/sstream:38,
                 from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:
/usr/include/c++/4.8/ostream:58:11: note: ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:0:
/usr/include/c++/4.8/sstream:502:11: error: use of deleted function ‘std::basic_stringbuf<char>& std::basic_stringbuf<char>::operator=(const std::basic_stringbuf<char>&)’
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/sstream:64:11: note: ‘std::basic_stringbuf<char>& std::basic_stringbuf<char>::operator=(const std::basic_stringbuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8/ios:43:0,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:
/usr/include/c++/4.8/streambuf:810:7: error: ‘std::basic_streambuf<_CharT, _Traits>& std::basic_streambuf<_CharT, _Traits>::operator=(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       operator=(const basic_streambuf&) { return _this; };
       ^
In file included from /home/anthony/app/dest-master_2/src/io/database_io.cpp:14:0:
/usr/include/c++/4.8/sstream:64:11: error: within this context
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
/home/anthony/app/dest-master_2/src/io/database_io.cpp: In member function ‘virtual bool dest::io::DatabaseLoaderLAND::loadShape(std::size_t, cv::Size, dest::core::Shape&)’:
/home/anthony/app/dest-master_2/src/io/database_io.cpp:442:22: error: use of deleted function ‘std::basic_stringstream<char>& std::basic_stringstream<char>::operator=(const std::basic_stringstream<char>&)’
                 str1 = std::stringstream(line);
                      ^
make[2]: *_\* [CMakeFiles/dest.dir/src/io/database_io.cpp.o] Error 1
make[1]: **\* [CMakeFiles/dest.dir/all] Error 2
make: **\* [all] Error 2
anthony@anthony-Inspiron-7420:~/app/dest-master_2/build$

**Comment by cheind** [comment]
Got it, will have a fix soon.
