### ISSUE TITLE
dest_align build error

### ISSUE THREAD

**Issue by AnaZou** [cheind/dest#6]
Hello,i have download your src code,and i follow your inductions。First,use cmake to build；After that i build it on vs2013，but i have come a problem with dest_align。It show the LNK2001 with dest.lib,how can i solve the problem

**Comment by cheind** [comment]
Hi, could you please post the full error log. The error you got means that dest itself didn't build, so dest_align cannot link it.

**Comment by AnaZou** [comment]
The follows is the full error log.
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z)，该符号在函数 "public: __cdecl cv::Mat::~Mat(void)" (??1Mat@cv@@QEAA@XZ) 中被引用
1>dest.lib(draw.obj) : error LNK2001: 无法解析的外部符号 "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z)
1>dest.lib(face_detector.obj) : error LNK2001: 无法解析的外部符号 "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z)
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "private: char \* __cdecl cv::String::allocate(unsigned __int64)" (?allocate@String@cv@@AEAAPEAD_K@Z)，该符号在函数 "public: __cdecl cv::String::String(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0String@cv@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2001: 无法解析的外部符号 "private: char \* __cdecl cv::String::allocate(unsigned __int64)" (?allocate@String@cv@@AEAAPEAD_K@Z)
1>dest.lib(face_detector.obj) : error LNK2001: 无法解析的外部符号 "private: char \* __cdecl cv::String::allocate(unsigned __int64)" (?allocate@String@cv@@AEAAPEAD_K@Z)
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)，该符号在函数 "public: __cdecl cv::String::~String(void)" (??1String@cv@@QEAA@XZ) 中被引用
1>dest.lib(draw.obj) : error LNK2001: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)
1>dest.lib(face_detector.obj) : error LNK2001: 无法解析的外部符号 "private: void __cdecl cv::String::deallocate(void)" (?deallocate@String@cv@@AEAAXXZ)
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::error(int,class cv::String const &,char const *,char const *,int)" (?error@cv@@YAXHAEBVString@1@PEBD1H@Z)，该符号在函数 "public: unsigned char \* __cdecl cv::Mat::ptr<unsigned char>(int)" (??$ptr@E@Mat@cv@@QEAAPEAEH@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2001: 无法解析的外部符号 "void __cdecl cv::error(int,class cv::String const &,char const *,char const *,int)" (?error@cv@@YAXHAEBVString@1@PEBD1H@Z)
1>dest.lib(face_detector.obj) : error LNK2001: 无法解析的外部符号 "void __cdecl cv::error(int,class cv::String const &,char const *,char const *,int)" (?error@cv@@YAXHAEBVString@1@PEBD1H@Z)
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::deallocate(void)" (?deallocate@Mat@cv@@QEAAXXZ)，该符号在函数 "public: void __cdecl cv::Mat::release(void)" (?release@Mat@cv@@QEAAXXZ) 中被引用
1>dest.lib(draw.obj) : error LNK2001: 无法解析的外部符号 "public: void __cdecl cv::Mat::deallocate(void)" (?deallocate@Mat@cv@@QEAAXXZ)
1>dest.lib(face_detector.obj) : error LNK2001: 无法解析的外部符号 "public: void __cdecl cv::Mat::deallocate(void)" (?deallocate@Mat@cv@@QEAAXXZ)
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::copySize(class cv::Mat const &)" (?copySize@Mat@cv@@QEAAXAEBV12@@Z)，该符号在函数 "public: class cv::Mat & __cdecl cv::Mat::operator=(class cv::Mat const &)" (??4Mat@cv@@QEAAAEAV01@AEBV01@@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2001: 无法解析的外部符号 "public: void __cdecl cv::Mat::copySize(class cv::Mat const &)" (?copySize@Mat@cv@@QEAAXAEBV12@@Z)
1>dest.lib(face_detector.obj) : error LNK2001: 无法解析的外部符号 "public: void __cdecl cv::Mat::copySize(class cv::Mat const &)" (?copySize@Mat@cv@@QEAAXAEBV12@@Z)
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::cvtColor(class cv::_InputArray const &,class cv::_OutputArray const &,int,int)" (?cvtColor@cv@@YAXAEBV_InputArray@1@AEBV_OutputArray@1@HH@Z)，该符号在函数 "void __cdecl dest::util::toDest(class cv::Mat const &,class Eigen::Matrix<unsigned char,-1,-1,1,-1,-1> &)" (?toDest@util@dest@@YAXAEBVMat@cv@@AEAV?$Matrix@E$0?0$0?0$00$0?0$0?0@Eigen@@@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2001: 无法解析的外部符号 "void __cdecl cv::cvtColor(class cv::_InputArray const &,class cv::_OutputArray const &,int,int)" (?cvtColor@cv@@YAXAEBV_InputArray@1@AEBV_OutputArray@1@HH@Z)
1>dest.lib(face_detector.obj) : error LNK2001: 无法解析的外部符号 "void __cdecl cv::cvtColor(class cv::_InputArray const &,class cv::_OutputArray const &,int,int)" (?cvtColor@cv@@YAXAEBV_InputArray@1@AEBV_OutputArray@1@HH@Z)
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "class cv::Mat __cdecl cv::imread(class cv::String const &,int)" (?imread@cv@@YA?AVMat@1@AEBVString@1@H@Z)，该符号在函数 main 中被引用
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "int __cdecl cv::waitKey(int)" (?waitKey@cv@@YAHH@Z)，该符号在函数 main 中被引用
1>dest_align.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::imshow(class cv::String const &,class cv::_InputArray const &)" (?imshow@cv@@YAXAEBVString@1@AEBV_InputArray@1@@Z)，该符号在函数 main 中被引用
1>dest.lib(draw.obj) : error LNK2019: 无法解析的外部符号 "class cv::_InputOutputArray const & __cdecl cv::noArray(void)" (?noArray@cv@@YAAEBV_InputOutputArray@1@XZ)，该符号在函数 "void __cdecl dest::util::drawShape(class cv::Mat &,class Eigen::Matrix<float,2,-1,0,2,-1> const &,int)" (?drawShape@util@dest@@YAXAEAVMat@cv@@AEBV?$Matrix@M$01$0?0$0A@$01$0?0@Eigen@@H@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::create(int,int const *,int)" (?create@Mat@cv@@QEAAXHPEBHH@Z)，该符号在函数 "public: void __cdecl cv::Mat::create(int,int,int)" (?create@Mat@cv@@QEAAXHHH@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl cv::normalize(class cv::_InputArray const &,class cv::_InputOutputArray const &,double,double,int,int,class cv::_InputArray const &)" (?normalize@cv@@YAXAEBV_InputArray@1@AEBV_InputOutputArray@1@NNHH0@Z)，该符号在函数 "void __cdecl dest::util::drawShape(class cv::Mat &,class Eigen::Matrix<float,2,-1,0,2,-1> const &,int)" (?drawShape@util@dest@@YAXAEAVMat@cv@@AEBV?$Matrix@M$01$0?0$0A@$01$0?0@Eigen@@H@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl cv::applyColorMap(class cv::_InputArray const &,class cv::_OutputArray const &,int)" (?applyColorMap@cv@@YAXAEBV_InputArray@1@AEBV_OutputArray@1@H@Z)，该符号在函数 "void __cdecl dest::util::drawShape(class cv::Mat &,class Eigen::Matrix<float,2,-1,0,2,-1> const &,int)" (?drawShape@util@dest@@YAXAEAVMat@cv@@AEBV?$Matrix@M$01$0?0$0A@$01$0?0@Eigen@@H@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl cv::line(class cv::_InputOutputArray const &,class cv::Point_<int>,class cv::Point_<int>,class cv::Scalar_<double> const &,int,int,int)" (?line@cv@@YAXAEBV_InputOutputArray@1@V?$Point_@H@1@1AEBV?$Scalar_@N@1@HHH@Z)，该符号在函数 "void __cdecl dest::util::drawRect(class cv::Mat &,class Eigen::Matrix<float,2,4,2,2,4> const &,class cv::Scalar_<double> const &)" (?drawRect@util@dest@@YAXAEAVMat@cv@@AEBV?$Matrix@M$01$03$01$01$03@Eigen@@AEBV?$Scalar_@N@4@@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl cv::circle(class cv::_InputOutputArray const &,class cv::Point_<int>,int,class cv::Scalar_<double> const &,int,int,int)" (?circle@cv@@YAXAEBV_InputOutputArray@1@V?$Point_@H@1@HAEBV?$Scalar_@N@1@HHH@Z)，该符号在函数 "void __cdecl dest::util::drawShape(class cv::Mat &,class Eigen::Matrix<float,2,-1,0,2,-1> const &,class cv::Scalar_<double> const &)" (?drawShape@util@dest@@YAXAEAVMat@cv@@AEBV?$Matrix@M$01$0?0$0A@$01$0?0@Eigen@@AEBV?$Scalar_@N@4@@Z) 中被引用
1>dest.lib(draw.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl cv::putText(class cv::_InputOutputArray const &,class cv::String const &,class cv::Point_<int>,int,double,class cv::Scalar_<double>,int,int,bool)" (?putText@cv@@YAXAEBV_InputOutputArray@1@AEBVString@1@V?$Point_@H@1@HNV?$Scalar_@N@1@HH_N@Z)，该符号在函数 "void __cdecl dest::util::drawShapeText(class cv::Mat &,class Eigen::Matrix<float,2,-1,0,2,-1> const &,class cv::Scalar_<double> const &)" (?drawShapeText@util@dest@@YAXAEAVMat@cv@@AEBV?$Matrix@M$01$0?0$0A@$01$0?0@Eigen@@AEBV?$Scalar_@N@4@@Z) 中被引用
1>dest.lib(face_detector.obj) : error LNK2019: 无法解析的外部符号 "public: __cdecl cv::Mat::Mat(class cv::Mat const &,class cv::Rect_<int> const &)" (??0Mat@cv@@QEAA@AEBV01@AEBV?$Rect_@H@1@@Z)，该符号在函数 "public: class cv::Mat __cdecl cv::Mat::operator()(class cv::Rect_<int> const &)const " (??RMat@cv@@QEBA?AV01@AEBV?$Rect_@H@1@@Z) 中被引用
1>dest.lib(face_detector.obj) : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::copyTo(class cv::_OutputArray const &)const " (?copyTo@Mat@cv@@QEBAXAEBV_OutputArray@2@@Z)，该符号在函数 "public: bool __cdecl dest::face::FaceDetector::detectFaces(class cv::Mat const &,class std::vector<class cv::Rect_<int>,class std::allocator<class cv::Rect_<int> > > &)const " (?detectFaces@FaceDetector@face@dest@@QEBA_NAEBVMat@cv@@AEAV?$vector@V?$Rect_@H@cv@@V?$allocator@V?$Rect_@H@cv@@@std@@@std@@@Z) 中被引用
1>dest.lib(face_detector.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl cv::equalizeHist(class cv::_InputArray const &,class cv::_OutputArray const &)" (?equalizeHist@cv@@YAXAEBV_InputArray@1@AEBV_OutputArray@1@@Z)，该符号在函数 "public: bool __cdecl dest::face::FaceDetector::detectFaces(class cv::Mat const &,class std::vector<class cv::Rect_<int>,class std::allocator<class cv::Rect_<int> > > &)const " (?detectFaces@FaceDetector@face@dest@@QEBA_NAEBVMat@cv@@AEAV?$vector@V?$Rect_@H@cv@@V?$allocator@V?$Rect_@H@cv@@@std@@@std@@@Z) 中被引用
1>dest.lib(face_detector.obj) : error LNK2019: 无法解析的外部符号 "public: __cdecl cv::CascadeClassifier::CascadeClassifier(void)" (??0CascadeClassifier@cv@@QEAA@XZ)，该符号在函数 "public: __cdecl dest::face::FaceDetector::data::data(void)" (??0data@FaceDetector@face@dest@@QEAA@XZ) 中被引用
1>dest.lib(face_detector.obj) : error LNK2019: 无法解析的外部符号 "public: __cdecl cv::CascadeClassifier::~CascadeClassifier(void)" (??1CascadeClassifier@cv@@QEAA@XZ)，该符号在函数 "int `public: __cdecl dest::face::FaceDetector::data::data(void)'::`1'::dtor$0" (?dtor$0@?0???0data@FaceDetector@face@dest@@QEAA@XZ@4HA) 中被引用
1>dest.lib(face_detector.obj) : error LNK2019: 无法解析的外部符号 "public: bool __cdecl cv::CascadeClassifier::load(class cv::String const &)" (?load@CascadeClassifier@cv@@QEAA_NAEBVString@2@@Z)，该符号在函数 "public: bool __cdecl dest::face::FaceDetector::loadClassifiers(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?loadClassifiers@FaceDetector@face@dest@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z) 中被引用
1>dest.lib(face_detector.obj) : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::CascadeClassifier::detectMultiScale(class cv::_InputArray const &,class std::vector<class cv::Rect_<int>,class std::allocator<class cv::Rect_<int> > > &,double,int,int,class cv::Size_<int>,class cv::Size_<int>)" (?detectMultiScale@CascadeClassifier@cv@@QEAAXAEBV_InputArray@2@AEAV?$vector@V?$Rect_@H@cv@@V?$allocator@V?$Rect_@H@cv@@@std@@@std@@NHHV?$Size_@H@2@2@Z)，该符号在函数 "public: bool __cdecl dest::face::FaceDetector::detectFaces(class cv::Mat const &,class std::vector<class cv::Rect_<int>,class std::allocator<class cv::Rect_<int> > > &)const " (?detectFaces@FaceDetector@face@dest@@QEBA_NAEBVMat@cv@@AEAV?$vector@V?$Rect_@H@cv@@V?$allocator@V?$Rect_@H@cv@@@std@@@std@@@Z) 中被引用
1>K:\tools\FaceLandmark\Build\Debug\dest_align.exe : fatal error LNK1120: 24 个无法解析的外部命令

**Comment by AnaZou** [comment]
I have solved the problem, i have misunderstand your instructions.Thanks for help

**Comment by cheind** [comment]
Great that you got it working. What confused you, anything I can adapt to avoid misunderstandings?

**Comment by AnaZou** [comment]
Any other dependencies?
Yes, those are inline included and are header only。I misunderstood this,i just set the include header without set the lib link in the vs2013。According to the error list before,it just mean that i haven't link the lib error.
I heve train the shape_predictor on the helen dataset with 194 landmarks,but when i test the model,it shows bad result  compare to dlib provided shape_predictor.I have try to adjust the param,but the model still perform bad,have u ever meet this problem?

**Comment by cheind** [comment]
Consider this closed. Please re-open one for quality issue if it persists.
