### ISSUE TITLE
debug fail

### ISSUE THREAD

**Issue by joe0327** [cheind/dest#7]
Everytime I use this project, Debug failed, But if I change to Release mode,It works! do you have any ideas of this question ? 
![qq 20161010171713](https://cloud.githubusercontent.com/assets/5153527/19231688/f7f6edda-8f0d-11e6-96b3-3b4648792241.png)

**Comment by joe0327** [comment]
problem solved, lower versions of OpenCV are not compatible with VS2015.

**Comment by cheind** [comment]
Ah great you solved it!
